### ISSUE TITLE
Readme genişletmesi

### ISSUE THREAD

**Issue by omersavas26** [malikmasis/TelephoneDirectory#1]
Merhaba Malik readme içerisinde proje ve kapsamı hakkında özet koyar mısın?

**Comment by malikmasis** [comment]
Merhabalar,
Projenin giriş dizininde mevcut. Gözden kaçırmış olabilir misin acaba?

**Comment by bariscanyilmaz** [comment]
Selam,
README dosyasında sadece projede kullanılan teknolojiler ve kurulumdan bahsedilmiş. Proje ve kapsam hakkında herhangi bir yazı yok.

**Comment by omersavas26** [comment]
Evet @bariscanyilmaz benden çok yaşayacak :)

**Comment by malikmasis** [comment]
Uyarılarınız için teşekkürler ederim. Gerekli düzenlemeler yapmaya çalışacağım.

**Comment by malikmasis** [comment]
Selamlar,
Geç de olsa bu konuyla ilgili bir blog yazısı hazırladım. Beni bu konuda teşvik ettiğiniz için teşekkürler ederim.
@omersavas26 @bariscanyilmaz 
https://medium.com/software-development-turkey/mikroservis-maceram-1e070463d0ea

**Comment by omersavas26** [comment]
Teşekkürler malik :)
